
# **Matriculator · Paso 4: marcado y formatos de datos**

Matriculator es a aplicacion hipotetica con la funcion de detectar matriculas de un parking para permitir el acceso al parking y otras funciones.

La interfaz web está planteada con **HTML/CSS/JavaScript**, el servidor puede usar **Node.js**, y el servicio de IA se plantea en **Python**. La comunicación entre servicios se realizaria mediante **JSON** y los registros podrian almacenarse o intercambiarse en **CSV**.

#### **Contenidos:**

1. Explicar **HTML, XML, JSON, Markdown y CSV**, indicando qué son, para qué sirven y sus características principales.
2. Relacionar cada formato con una parte concreta de Matriculator.
3. Identificar las principales librerías de Python para leer **HTML, CSV y JSON**.
4. Incluir una tabla Markdown con librerías equivalentes en **R**.
5. Inventar y parsear un HTML que represente una interfaz de usuario de Matriculator.
6. Inventar y parsear un JSON con nuevos datos de entrada sintéticos.


## **1 · HTML, XML, JSON, Markdown y CSV**

<div style="border:1px solid #cbd5e1; border-radius:12px; padding:18px 20px; margin:14px 0; background:#f8fafc;">

### **HTML**

**¿Qué es?**  
Es el lenguaje fundamental con el que se estructuran y maquetan las páginas web. Es el **esqueleto** de la pagina web: no define la lógica, ni los colores, sino dónde va cada elemento (un título, un formulario, un botón o una imagen).

**¿Para qué sirve?**  
Sirve para definir el contenido visible de una aplicación web y permitir que el usuario interactúe con ella enviando datos, pulsando botones o cargando archivos.

**Características principales**
<ul>
<li><u>Etiquetas jerárquicas:</u> Se organiza mediante etiquetas que se abren y cierran (como <code>&lt;main&gt;</code> o <code>&lt;form&gt;</code>) y que se anidan formando un árbol de elementos.</li>
<li><u>Elementos semánticos y atributos:</u> Usa etiquetas específicas (<code>&lt;header&gt;</code>, <code>&lt;section&gt;</code>, <code>&lt;table&gt;</code>) y atributos (<code>id</code>, <code>class</code>, <code>action</code>) para definir la función de cada bloque.</li>
<li><u>Interacción de usuario:</u> Incluye controles de entrada como botones, cajas de texto, desplegables y selecciones de archivos.</li>
</ul>

**Integración en Matriculator**  
Se usaria para crear la interfaz de la web (Frontend). Donde se encontrara con la seleccion de camara, la carga de la fotografia de la matricula y la visualizacion con los resultados del analisis.
</div>

<div style="border:1px solid #cbd5e1; border-radius:12px; padding:18px 20px; margin:14px 0; background:#f8fafc;">

### **XML (eXtensible Markup Language)**

**¿Qué es?**  
Es un lenguaje de marcado extensible. En XML las etiquetas las crea el propio desarrollador para representar sus datos de forma personalizada.

**¿Para qué sirve?**  
Sirve para almacenar y transportar datos estructurados entre distintos sistemas de forma clara, organizada y fácil de interpretar.

**Características principales**
<ul>
<li><u>Etiquetas personalizadas:</u> Puedes crear etiquetas según tu dominio (por ejemplo, <code>&lt;camara&gt;</code>, <code>&lt;zona&gt;</code>, <code>&lt;resolucion&gt;</code>), haciendo que el archivo sea entendible por humanos y máquinas.</li>
<li><u>Estructura estricta en árbol:</u> Tiene una estructura muy ordenada: debe tener un único elemento principal y cerrar correctamente todas las etiquetas.”</li>
<li><u>Validación por esquemas:</u> Permite validar el contenido mediante reglas para comprobar que la estructura no tenga errores ni campos faltantes.</li>
</ul>

**Integracion en Matriculator**  
Se utiliza como apoyo. Aunque no es el formato principal de la aplicación, puede servir para guardar la configuración de las cámaras o para compartir datos con otros sistemas del parking que trabajen con XML.

</div>

<div style="border:1px solid #cbd5e1; border-radius:12px; padding:18px 20px; margin:14px 0; background:#f8fafc;">

### **JSON (JavaScript Object Notation)**

**¿Qué es?**  
Es un formato de texto superligero para el intercambio de datos. Se basa en la forma en que JavaScript representa objetos y listas, siendo hoy el estándar principal en el desarrollo web y APIs.

**¿Para qué sirve?**  
Sirve para comunicar aplicaciones o capas independientes (por ejemplo, para enviar los datos de la web al servidor y de ahí al servicio de Inteligencia Artificial).

**Características principales**
<ul>
<li><u>Pares clave-valor y listas:</u> Organiza la información en objetos (<code>{"camara": "CAM-01"}</code>) y arrays (<code>[1, 2, 3]</code>).</li>
<li><u>Soporte de anidamiento:</u> Permite incluir objetos dentro de otros objetos, representando estructuras complejas de forma ordenada.</li>
<li><u>Procesamiento rápido y universal:</u> Ocupa poco espacio en red y prácticamente cualquier lenguaje (Python, JavaScript, R, etc.) puede leerlo y escribirlo de forma nativa.</li>
</ul>

**Integracion en Matriculator**  
Es la API de la web. Cuando la web o el servidor Node.js solicitan analizar una imagen, empaquetan la solicitud en un JSON y la envían al servicio de IA en Python, el cual responde con otro JSON que contiene la matrícula detectada, el nivel de confianza y el estado.

</div>

<div style="border:1px solid #cbd5e1; border-radius:12px; padding:18px 20px; margin:14px 0; background:#f8fafc;">

### **CSV (Comma-Separated Values)**

**¿Qué es?**  
Es la forma más sencilla y habitual de guardar datos en forma de tabla (filas y columnas) dentro de un archivo de texto plano.

**¿Para qué sirve?**  
Sirve para almacenar e intercambiar conjuntos de datos tabulares masivos, permitiendo abrirlos tanto en hojas de cálculo (Excel, Google Sheets) como en librerías de análisis de datos (Pandas, R).

**Características principales**
<ul>
<li><u>Estructura simple delimitada:</u> Cada línea del fichero es una fila, y cada columna se separa por un delimitador (habitualmente comas <code>,</code> o puntos y comas <code>;</code>).</li>
<li><u>Cabecera opcional:</u> La primera fila suele contener los nombres de las columnas (<code>fecha</code>, <code>camara</code>, <code>matricula</code>, <code>confianza</code>).</li>
<li><u>Texto plano y ligero:</u> Al no guardar estilos, colores ni fórmulas, ocupa muy poco espacio en disco y es muy rápido de cargar.</li>
</ul>

**Integracion en Matriculator**  
Se utiliza para **registros históricos y análisis de datos**. Por ejemplo, en la web se carga el archivo <code>data/trends_web.csv</code> para alimentar los gráficos de tendencias, y tambien se podria emplear para exportar o almacenar el registro acumulado de las lecturas de matrículas en el parking.

</div>

<div style="border:1px solid #cbd5e1; border-radius:12px; padding:18px 20px; margin:14px 0; background:#f8fafc;">

### **Markdown**

**¿Qué es?**  
Es un lenguaje de marcado muy ligero diseñado para dar formato a textos utilizando símbolos sencillos del teclado (como <code>#</code> para títulos, <code>*</code> para listas o <code>**</code> para negritas).

**¿Para qué sirve?**  
Sirve para redactar documentos de forma cómoda y limpia en texto plano, con la ventaja de que se pueden convertir automáticamente en páginas web, cuadernos interactivos o PDF.

**Características principales**
<ul>
<li><u>Sintaxis ágil y legible:</u> Permite escribir y leer el documento directamente en texto plano sin distracciones visuales de código complejo.</li>
<li><u>Soporte de contenido enriquecido:</u> Permite incluir encabezados, tablas, bloques de código, enlaces, citas y listas ordenadas.</li>
<li><u>Estándar en documentación:</u> Es el formato universal usado en plataformas de software como GitHub y en entornos analíticos como Jupyter Notebooks.</li>
</ul>

**Integracion en Matriculator**  
Se encarga de la documentación y presentación del proyecto. Se utiliza para redactar el archivo README.md del repositorio, guías de instalación y las celdas explicativas de este notebook.

</div>


## **2 · Librerías principales de Python para leer HTML, CSV y JSON**

<table style="font-size: 1.25em; width: 100%; border-collapse: collapse; text-align: left;">
  <thead>
    <tr style="border-bottom: 2px solid #888; background-color: rgba(150, 150, 150, 0.1);">
      <th style="padding: 12px;">Formato</th>
      <th style="padding: 12px;">Librería</th>
      <th style="padding: 12px;">Tipo</th>
      <th style="padding: 12px;">Uso habitual</th>
    </tr>
  </thead>
  <tbody>
    <tr style="border-bottom: 1px solid #ddd;">
      <td style="padding: 12px;"><strong>HTML</strong></td>
      <td style="padding: 12px;"><code>html.parser</code></td>
      <td style="padding: 12px;">Estándar</td>
      <td style="padding: 12px;">Parser HTML básico incluido en Python.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ddd;">
      <td style="padding: 12px;"><strong>HTML</strong></td>
      <td style="padding: 12px;"><code>BeautifulSoup</code> (<code>bs4</code>)</td>
      <td style="padding: 12px;">Externa</td>
      <td style="padding: 12px;">Buscar, navegar y extraer información de etiquetas HTML de forma sencilla.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ddd;">
      <td style="padding: 12px;"><strong>HTML</strong></td>
      <td style="padding: 12px;"><code>lxml</code></td>
      <td style="padding: 12px;">Externa</td>
      <td style="padding: 12px;">Parser rápido para HTML y XML.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ddd;">
      <td style="padding: 12px;"><strong>CSV</strong></td>
      <td style="padding: 12px;"><code>csv</code></td>
      <td style="padding: 12px;">Estándar</td>
      <td style="padding: 12px;">Leer y escribir filas de ficheros CSV.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ddd;">
      <td style="padding: 12px;"><strong>CSV</strong></td>
      <td style="padding: 12px;"><code>pandas.read_csv()</code></td>
      <td style="padding: 12px;">Externa</td>
      <td style="padding: 12px;">Cargar CSV directamente en un <code>DataFrame</code> para análisis y tratamiento tabular.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ddd;">
      <td style="padding: 12px;"><strong>JSON</strong></td>
      <td style="padding: 12px;"><code>json</code></td>
      <td style="padding: 12px;">Estándar</td>
      <td style="padding: 12px;">Leer JSON desde texto o fichero mediante <code>json.loads()</code> / <code>json.load()</code>.</td>
    </tr>
    <tr>
      <td style="padding: 12px;"><strong>JSON</strong></td>
      <td style="padding: 12px;"><code>pandas.read_json()</code> / <code>pandas.json_normalize()</code></td>
      <td style="padding: 12px;">Externa</td>
      <td style="padding: 12px;">Convertir JSON, especialmente datos anidados, en estructuras tabulares.</td>
    </tr>
  </tbody>
</table>

Para este notebook utilizaremos principalmente `BeautifulSoup` para HTML, `csv`/`pandas` para CSV y `json`/`pandas` para JSON.

In [ ]:
import json
import csv
import io
import xml.etree.ElementTree as ET

import pandas as pd
from bs4 import BeautifulSoup

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.


## **3 · Equivalentes en R**

La siguiente tabla resume alternativas habituales en R para realizar las mismas tareas. Se deja en **Markdown**, tal como pide el enunciado.


| Formato | Python | R | Uso equivalente |
|---|---|---|---|
| **HTML** | `BeautifulSoup`, `lxml` | `rvest`, `xml2` | Leer, navegar y extraer elementos de páginas HTML. |
| **CSV** | `csv`, `pandas.read_csv()` | `read.csv()`, `readr::read_csv()`, `data.table::fread()` | Leer datos tabulares delimitados. |
| **JSON** | `json`, `pandas.read_json()`, `json_normalize()` | `jsonlite::fromJSON()`, `rjson` | Convertir JSON en listas/estructuras y trabajar con datos anidados. |
| **XML** | `xml.etree.ElementTree`, `lxml` | `xml2` | Leer y recorrer documentos XML. |


## **4 · HTML inventado de la interfaz de usuario**

Para utilizar Python y la libreria Beatiful Soup para **leer el código fuente y extraer información especifica**. Esto nos permite analizar datos de paginas web de manera automatizada (web scraping).Para hacer un ejemplo inventamos una pequeña interfaz coherente con Matriculator. La pantalla permite:

- seleccionar una imagen de prueba;
- seleccionar la cámara;
- iniciar el análisis;
- visualizar la matrícula detectada, la confianza y el estado.

Aunque este escrito el código HTML de una interfaz visual, **nuestro objetivo aquí no es "dibujar" la página web** ni interactuar visualmente con ella (eso es tarea de un navegador web como Chrome o Firefox).

In [ ]:

html_interfaz = """
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Matriculator · Panel de pruebas</title>
</head>
<body>
  <header>
    <h1>Matriculator</h1>
    <p>Detección de matrículas en imágenes de prueba</p>
  </header>

  <main>
    <form id="analisis" action="/api/analizar" method="post">
      <label for="imagen">Imagen de prueba</label>
      <input
        type="file"
        id="imagen"
        name="imagen"
        accept=".jpg,.jpeg,.png"
        required
      >

      <label for="camara">Cámara</label>
      <select id="camara" name="camara_id">
        <option value="CAM-01">Entrada norte</option>
        <option value="CAM-02">Salida sur</option>
      </select>

      <button type="submit">Analizar imagen</button>
    </form>

    <section id="resultado" aria-label="Resultado del análisis">
      <h2>Último resultado</h2>
      <table>
        <thead>
          <tr>
            <th>Matrícula</th>
            <th>Confianza</th>
            <th>Estado</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1234ABC</td>
            <td>0.94</td>
            <td>OK</td>
          </tr>
        </tbody>
      </table>
    </section>
  </main>
</body>
</html>
"""

soup = BeautifulSoup(html_interfaz, "html.parser")

print("Título:", soup.title.get_text(strip=True))
print("Formulario:", soup.find("form")["action"])
print("Cámaras:", [op["value"] for op in soup.select("#camara option")])
print("Texto del botón:", soup.find("button").get_text(strip=True))

Título: Matriculator · Panel de pruebas
Formulario: /api/analizar
Cámaras: ['CAM-01', 'CAM-02']
Texto del botón: Analizar imagen

In [ ]:

# Extraemos la tabla HTML y la convertimos en un DataFrame.
tabla = soup.find("table")
filas = [
    [celda.get_text(" ", strip=True) for celda in fila.find_all(["th", "td"])]
    for fila in tabla.find_all("tr")
]

df_html = pd.DataFrame(filas[1:], columns=filas[0])
df_html

  Matrícula Confianza Estado
0   1234ABC      0.94     OK


### ¿Dónde interviene este HTML?

El HTML representa la **capa de presentación**: es la estructura que el navegador utiliza para mostrar controles de entrada y resultados. En la propuesta real, `index.html` cumple precisamente esta función y contiene la interfaz de Matriculator, incluida la sección del Paso 4 y el enlace al notebook.


## **5 · JSON**
Inventado con nuevos datos de entrada sintéticos ahora simulamos los datos que podrían llegar al backend antes de enviarse al servicio de IA. Incluimos un lote, el origen de los datos y varias imágenes con información de cámara.

`ruta_imagen` representa la ubicación de cada fichero de prueba.

In [ ]:

json_entrada = """
{
  "lote": "PRUEBA-2026-09",
  "origen": "banco_de_pruebas_sintetico",
  "aplicacion": "Matriculator",
  "imagenes": [
    {
      "id": 101,
      "ruta_imagen": "pruebas/parking_001.jpg",
      "camara": {
        "id": "CAM-01",
        "zona": "entrada_norte",
        "resolucion": "1920x1080",
        "iluminacion": "dia"
      }
    },
    {
      "id": 102,
      "ruta_imagen": "pruebas/parking_002.jpg",
      "camara": {
        "id": "CAM-01",
        "zona": "entrada_norte",
        "resolucion": "1920x1080",
        "iluminacion": "noche"
      }
    },
    {
      "id": 103,
      "ruta_imagen": "pruebas/parking_003.png",
      "camara": {
        "id": "CAM-02",
        "zona": "salida_sur",
        "resolucion": "1280x720",
        "iluminacion": "dia"
      }
    }
  ]
}
"""

datos = json.loads(json_entrada)

print("Lote:", datos["lote"])
print("Origen:", datos["origen"])
print("Número de imágenes:", len(datos["imagenes"]))

Lote: PRUEBA-2026-09
Origen: banco_de_pruebas_sintetico
Número de imágenes: 3

In [ ]:

# json_normalize aplana el objeto anidado "camara"
df_json = pd.json_normalize(datos["imagenes"], sep="_")
df_json

,id,ruta_imagen,camara_id,camara_zona,camara_resolucion,camara_iluminacion
0,101,pruebas/parking_001.jpg,CAM-01,entrada_norte,1920x1080,dia
1,102,pruebas/parking_002.jpg,CAM-01,entrada_norte,1920x1080,noche
2,103,pruebas/parking_003.png,CAM-02,salida_sur,1280x720,dia

El **JSON está diseñado específicamente para estructurar datos** de forma que una máquina los consuma rápidamente. Por eso, herramientas como `pandas.json_normalize()` nos permiten convertir estas estructuras directamente en tablas con una sola línea de código, sin necesidad de buscar etiquetas.


### ¿Dónde interviene este JSON?

El JSON representa el **intercambio de datos entre componentes**. En la arquitectura propuesta, el navegador/servidor puede enviar información al servicio de IA y recibir de él una respuesta estructurada. El `index.html` describe explícitamente la conexión entre el servidor Node.js y el servicio de IA Python mediante JSON.

Un resultado hipotético podría tener esta forma:

In [ ]:

json_resultado = {
    "imagen_id": 101,
    "matricula": "1234ABC",
    "confianza": 0.94,
    "estado": "OK",
    "requiere_revision": False
}

print(json.dumps(json_resultado, ensure_ascii=False, indent=2))

{
  "imagen_id": 101,
  "matricula": "1234ABC",
  "confianza": 0.94,
  "estado": "OK",
  "requiere_revision": false
}


## **6 · XML**

Ejemplo breve y relación con Matriculator. Aunque el intercambio principal de la aplicación se plantea con JSON, XML puede ser útil para una **configuración o intercambio auxiliar** con sistemas que ya trabajen con XML. Por ejemplo, podemos representar de forma jerárquica la configuración de cámaras.

In [ ]:

xml_camaras = """
<camaras>
  <camara id="CAM-01" zona="entrada_norte">
    <resolucion>1920x1080</resolucion>
    <iluminacion>dia</iluminacion>
  </camara>
  <camara id="CAM-02" zona="salida_sur">
    <resolucion>1280x720</resolucion>
    <iluminacion>dia</iluminacion>
  </camara>
</camaras>
"""

raiz = ET.fromstring(xml_camaras)
configuracion = [
    {
        "id": camara.attrib["id"],
        "zona": camara.attrib["zona"],
        "resolucion": camara.findtext("resolucion"),
        "iluminacion": camara.findtext("iluminacion")
    }
    for camara in raiz.findall("camara")
]

pd.DataFrame(configuracion)

       id           zona resolucion iluminacion
0  CAM-01  entrada_norte  1920x1080         dia
1  CAM-02     salida_sur   1280x720         dia


## **7 · CSV**

 Registros de detecciones y datos de Trends. CSV dentro de la propuesta: transportar datos tabulares que el navegador puede representar. Además, es un formato adecuado para exportar registros de detecciones.

Ejemplo:

In [ ]:

csv_registros = """fecha,camara_id,matricula,confianza,estado
2026-09-23T09:15,CAM-01,1234ABC,0.94,OK
2026-09-23T09:16,CAM-01,,0.41,REVISION_HUMANA
2026-09-23T09:18,CAM-02,5678DEF,0.89,OK
"""

df_csv = pd.read_csv(io.StringIO(csv_registros))
df_csv


## **8 · Markdown**

Markdown no sería un formato de comunicación entre la interfaz y el servicio de IA. Su función en el proyecto es principalmente **documental**: README, explicaciones del trabajo, tablas, decisiones técnicas y notebooks como este.

Por ejemplo, esta propia celda está escrita en Markdown y permite documentar de forma legible el funcionamiento de Matriculator.


## **9 · Conclusión**

Los cinco formatos tienen funciones diferentes y complementarias:

- **HTML** → estructura de la interfaz web de Matriculator.
- **JSON** → intercambio de datos entre navegador/servidor y servicio de IA.
- **CSV** → datos tabulares, como los datos de Google Trends y posibles registros.
- **XML** → formato alternativo para configuraciones o intercambios auxiliares que requieran una estructura jerárquica.
- **Markdown** → documentación del proyecto y del desarrollo.

La elección no significa que todos tengan que utilizarse con la misma importancia: en esta aplicación, **HTML y JSON son centrales**, CSV tiene un uso claro para datos tabulares, mientras que XML y Markdown cumplen funciones auxiliares/documentales.